/* ============================================================
   SARKARI UPDATES — Data Layer
   All content is sample/placeholder data for demonstration.
   ============================================================ */

const CATEGORIES = [
  { id: "all", label: "All Updates", icon: "grid" },
  { id: "job", label: "Sarkari Jobs", icon: "briefcase" },
  { id: "admit", label: "Admit Card", icon: "ticket" },
  { id: "result", label: "Results", icon: "trophy" },
  { id: "answer", label: "Answer Key", icon: "key" },
  { id: "syllabus", label: "Syllabus", icon: "book" },
];

const DEPARTMENTS = [
  "SSC",
  "UPSC",
  "Railway",
  "Banking",
  "State Police",
  "Teaching",
  "Defence",
  "Health",
];

const POSTS = [
  {
    id: 1,
    type: "job",
    title: "SSC CGL 2026 — Combined Graduate Level Examination",
    org: "Staff Selection Commission",
    dept: "SSC",
    date: "2026-08-15",
    lastDate: "2026-09-10",
    vacancies: "17727",
    category: ["SSC", "Graduate"],
    tags: ["Online Form", "Graduation", "All India"],
    applyUrl: "#apply-ssc-cgl",
    officialUrl: "https://ssc.gov.in",
    salary: "₹25,500 – ₹1,51,100",
    short: "SSC CGL 2026 notification out. Apply online for 17,727 Group B & C vacancies before 10 September 2026.",
  },
  {
    id: 2,
    type: "job",
    title: "UPSC Civil Services (IAS/IPS) Prelims 2027",
    org: "Union Public Service Commission",
    dept: "UPSC",
    date: "2026-08-12",
    lastDate: "2026-09-14",
    vacancies: "980",
    category: ["UPSC", "Graduate"],
    tags: ["UPSC", "IAS", "IPS"],
    applyUrl: "#apply-upsc-cse",
    officialUrl: "https://upsc.gov.in",
    salary: "₹56,100 – ₹2,50,000",
    short: "UPSC CSE 2027 notification released. Prelims to be held in May 2027. Apply online before 14 September 2026.",
  },
  {
    id: 3,
    type: "admit",
    title: "Railway RRB NTPC 2026 — Admit Card Released",
    org: "Railway Recruitment Board",
    dept: "Railway",
    date: "2026-08-14",
    lastDate: "2026-08-20",
    vacancies: "11558",
    category: ["Railway", "All"],
    tags: ["Admit Card", "CBT 1"],
    applyUrl: "#download-rrb-admit",
    officialUrl: "https://rrb.gov.in",
    short: "RRB NTPC CBT Stage 1 admit card available for download. Exam from 24 August 2026.",
  },
  {
    id: 4,
    type: "result",
    title: "UP Police Constable 2026 — Final Result Declared",
    org: "UP Police Recruitment Board",
    dept: "State Police",
    date: "2026-08-13",
    lastDate: "2026-08-13",
    vacancies: "60244",
    category: ["Police", "12th Pass"],
    tags: ["Final Result", "Merit List"],
    applyUrl: "#result-up-police",
    officialUrl: "https://uppbpb.gov.in",
    short: "UP Police Constable final result and merit list declared. Check your roll number now.",
  },
  {
    id: 5,
    type: "answer",
    title: "SSC MTS 2026 — Answer Key Released",
    org: "Staff Selection Commission",
    dept: "SSC",
    date: "2026-08-11",
    lastDate: "2026-08-16",
    vacancies: "9123",
    category: ["SSC", "10th Pass"],
    tags: ["Answer Key", "Objection"],
    applyUrl: "#answer-key-mts",
    officialUrl: "https://ssc.gov.in",
    short: "SSC MTS 2026 provisional answer key available. Raise objections before 16 August 2026.",
  },
  {
    id: 6,
    type: "job",
    title: "IBPS PO 2026 — Probationary Officer Recruitment",
    org: "Institute of Banking Personnel Selection",
    dept: "Banking",
    date: "2026-08-10",
    lastDate: "2026-08-31",
    vacancies: "4500",
    category: ["Banking", "Graduate"],
    tags: ["Bank Job", "IBPS PO"],
    applyUrl: "#apply-ibps-po",
    officialUrl: "https://ibps.in",
    salary: "₹48,000 – ₹92,000",
    short: "IBPS PO 2026 notification out. Online applications open till 31 August 2026. Prelims in October.",
  },
  {
    id: 7,
    type: "syllabus",
    title: "SSC GD Constable 2027 — Syllabus & Exam Pattern",
    org: "Staff Selection Commission",
    dept: "SSC",
    date: "2026-08-09",
    lastDate: "2026-08-09",
    vacancies: "39481",
    category: ["SSC", "10th Pass"],
    tags: ["Syllabus", "Exam Pattern"],
    applyUrl: "#syllabus-gd",
    officialUrl: "https://ssc.gov.in",
    short: "Complete SSC GD 2027 syllabus, exam pattern and marking scheme — download PDF.",
  },
  {
    id: 8,
    type: "job",
    title: "Bihar Police Constable 2026 — 19,000+ Vacancies",
    org: "Bihar Police Recruitment",
    dept: "State Police",
    date: "2026-08-08",
    lastDate: "2026-09-05",
    vacancies: "19343",
    category: ["Police", "12th Pass"],
    tags: ["Online Form", "State Job"],
    applyUrl: "#apply-bihar-police",
    officialUrl: "https://csbc.bihar.gov.in",
    salary: "₹25,000 – ₹81,100",
    short: "Bihar Police Constable recruitment 2026 — apply for 19,343 posts before 5 September.",
  },
  {
    id: 9,
    type: "admit",
    title: "UPSC NDA/NA II 2026 — Admit Card Released",
    org: "Union Public Service Commission",
    dept: "UPSC",
    date: "2026-08-07",
    lastDate: "2026-08-30",
    vacancies: "404",
    category: ["UPSC", "12th Pass"],
    tags: ["Admit Card", "Defence"],
    applyUrl: "#download-nda-admit",
    officialUrl: "https://upsc.gov.in",
    short: "UPSC NDA/NA II 2026 e-admit card available. Written exam on 31 August 2026.",
  },
  {
    id: 10,
    type: "job",
    title: "RRB ALP 2026 — Assistant Loco Pilot Recruitment",
    org: "Railway Recruitment Board",
    dept: "Railway",
    date: "2026-08-05",
    lastDate: "2026-08-28",
    vacancies: "18799",
    category: ["Railway", "ITI/Diploma"],
    tags: ["Online Form", "ITI"],
    applyUrl: "#apply-rrb-alp",
    officialUrl: "https://rrb.gov.in",
    salary: "₹19,900 – ₹35,400",
    short: "RRB ALP 2026 notification out. Apply for 18,799 Assistant Loco Pilot posts before 28 August.",
  },
  {
    id: 11,
    type: "result",
    title: "CTET July 2026 — Result Declared",
    org: "Central Board of Secondary Education",
    dept: "Teaching",
    date: "2026-08-04",
    lastDate: "2026-08-04",
    vacancies: "0",
    category: ["Teaching", "Graduate"],
    tags: ["Result", "CTET"],
    applyUrl: "#result-ctet",
    officialUrl: "https://ctet.nic.in",
    short: "CTET July 2026 result released on the official website. Download score card now.",
  },
  {
    id: 12,
    type: "job",
    title: "SBI Clerk 2026 — Junior Associate Recruitment",
    org: "State Bank of India",
    dept: "Banking",
    date: "2026-08-02",
    lastDate: "2026-08-25",
    vacancies: "13735",
    category: ["Banking", "Graduate"],
    tags: ["Bank Job", "SBI Clerk"],
    applyUrl: "#apply-sbi-clerk",
    officialUrl: "https://sbi.co.in",
    salary: "₹18,000 – ₹40,000",
    short: "SBI Clerk 2026 notification — apply for 13,735 Junior Associate posts before 25 August.",
  },
  {
    id: 13,
    type: "job",
    title: "AIIMS Nursing Officer 2026 — Recruitment",
    org: "All India Institute of Medical Sciences",
    dept: "Health",
    date: "2026-07-30",
    lastDate: "2026-08-22",
    vacancies: "1877",
    category: ["Health", "Nursing"],
    tags: ["Online Form", "B.Sc Nursing"],
    applyUrl: "#apply-aiims-nursing",
    officialUrl: "https://aiims.gov.in",
    salary: "₹44,900 – ₹1,42,400",
    short: "AIIMS Nursing Officer recruitment 2026 — 1,877 vacancies, apply before 22 August.",
  },
  {
    id: 14,
    type: "syllabus",
    title: "IBPS Clerk 2027 — Syllabus & Exam Pattern",
    org: "Institute of Banking Personnel Selection",
    dept: "Banking",
    date: "2026-07-28",
    lastDate: "2026-07-28",
    vacancies: "0",
    category: ["Banking", "Graduate"],
    tags: ["Syllabus", "Prelims"],
    applyUrl: "#syllabus-ibps-clerk",
    officialUrl: "https://ibps.in",
    short: "IBPS Clerk 2027 detailed syllabus, exam pattern, section-wise marks and negative marking.",
  },
  {
    id: 15,
    type: "admit",
    title: "SSC CHSL 2026 — Admit Card Released",
    org: "Staff Selection Commission",
    dept: "SSC",
    date: "2026-07-27",
    lastDate: "2026-08-18",
    vacancies: "3712",
    category: ["SSC", "12th Pass"],
    tags: ["Admit Card", "Tier 1"],
    applyUrl: "#download-chsl-admit",
    officialUrl: "https://ssc.gov.in",
    short: "SSC CHSL Tier 1 admit card available for download by region. Exam from 19 August 2026.",
  },
  {
    id: 16,
    type: "job",
    title: "Rajasthan Patwari 2026 — 8,500+ Vacancies",
    org: "Rajasthan Staff Selection Board",
    dept: "State Police",
    date: "2026-07-25",
    lastDate: "2026-08-20",
    vacancies: "8512",
    category: ["State", "Graduate"],
    tags: ["Online Form", "Patwari"],
    applyUrl: "#apply-rajasthan-patwari",
    officialUrl: "https://rssb.rajasthan.gov.in",
    salary: "₹20,000 – ₹65,000",
    short: "Rajasthan Patwari recruitment 2026 — 8,512 posts, apply online before 20 August.",
  },
  {
    id: 17,
    type: "result",
    title: "AIIMS Nursing Result 2026 — Merit List Out",
    org: "All India Institute of Medical Sciences",
    dept: "Health",
    date: "2026-07-24",
    lastDate: "2026-07-24",
    vacancies: "1877",
    category: ["Health", "Nursing"],
    tags: ["Result", "Merit List"],
    applyUrl: "#result-aiims",
    officialUrl: "https://aiims.gov.in",
    short: "AIIMS B.Sc Nursing 2026 final result and merit list declared.",
  },
  {
    id: 18,
    type: "job",
    title: "Indian Army Agniveer 2026 — Online Form",
    org: "Indian Army",
    dept: "Defence",
    date: "2026-07-22",
    lastDate: "2026-08-15",
    vacancies: "20000",
    category: ["Defence", "10th/12th"],
    tags: ["Agniveer", "Army"],
    applyUrl: "#apply-agniveer",
    officialUrl: "https://joinindianarmy.nic.in",
    salary: "₹30,000 – ₹40,000",
    short: "Indian Army Agniveer Rally 2026 — apply for Soldier, Technical and Clerk posts before 15 August.",
  },
  {
    id: 19,
    type: "answer",
    title: "UPSC CDS II 2026 — Answer Key Released",
    org: "Union Public Service Commission",
    dept: "UPSC",
    date: "2026-07-20",
    lastDate: "2026-07-26",
    vacancies: "457",
    category: ["UPSC", "Graduate"],
    tags: ["Answer Key", "CDS"],
    applyUrl: "#answer-key-cds",
    officialUrl: "https://upsc.gov.in",
    short: "UPSC CDS II 2026 answer key released. Submit objections till 26 July 2026.",
  },
  {
    id: 20,
    type: "syllabus",
    title: "UPSC IAS Mains 2026 — Optional Subjects Syllabus",
    org: "Union Public Service Commission",
    dept: "UPSC",
    date: "2026-07-18",
    lastDate: "2026-07-18",
    vacancies: "0",
    category: ["UPSC", "Graduate"],
    tags: ["Syllabus", "Mains"],
    applyUrl: "#syllabus-upsc-mains",
    officialUrl: "https://upsc.gov.in",
    short: "Download UPSC IAS Mains optional subjects syllabus and exam pattern PDF.",
  },
];

const TICKER = [
  "SSC CGL 2026 — Apply for 17,727 posts before 10 Sep",
  "RRB NTPC Admit Card Released — Download Now",
  "UP Police Constable Final Result Declared",
  "IBPS PO 2026 Applications Open till 31 Aug",
  "CTET July 2026 Result Out — Check Score",
  "UPSC CSE 2027 Notification Released",
  "Bihar Police Constable — 19,343 Vacancies",
  "SSC MTS Answer Key Available for Objections",
];

const STATS = [
  { value: 48000, suffix: "+", label: "Active Job Seekers" },
  { value: 1200, suffix: "+", label: "Notifications Posted" },
  { value: 38, suffix: "", label: "Govt Departments Covered" },
  { value: 24, suffix: "/7", label: "Fresh Updates" },
];
